<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Phonenumbers', 'doctrine');

/**
 * BasePhonenumbers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $number
 * 
 * @method integer      getId()     Returns the current record's "id" value
 * @method string       getNumber() Returns the current record's "number" value
 * @method Phonenumbers setId()     Sets the current record's "id" value
 * @method Phonenumbers setNumber() Sets the current record's "number" value
 * 
 * @package    quanaudio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhonenumbers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('phonenumbers');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('number', 'string', 24, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 24,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}