<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Type', 'doctrine');

/**
 * BaseType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtype
 * @property string $name
 * @property integer $idparent
 * @property Doctrine_Collection $Audio
 * 
 * @method integer             getIdtype()   Returns the current record's "idtype" value
 * @method string              getName()     Returns the current record's "name" value
 * @method integer             getIdparent() Returns the current record's "idparent" value
 * @method Doctrine_Collection getAudio()    Returns the current record's "Audio" collection
 * @method Type                setIdtype()   Sets the current record's "idtype" value
 * @method Type                setName()     Sets the current record's "name" value
 * @method Type                setIdparent() Sets the current record's "idparent" value
 * @method Type                setAudio()    Sets the current record's "Audio" collection
 * 
 * @package    quanaudio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type');
        $this->hasColumn('idtype', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('idparent', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Audio', array(
             'local' => 'idtype',
             'foreign' => 'idtype'));
    }
}