<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Slide', 'doctrine');

/**
 * BaseSlide
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idslide
 * @property string $title
 * @property string $description
 * @property string $content
 * @property string $image
 * @property string $advertisement
 * 
 * @method integer getIdslide()       Returns the current record's "idslide" value
 * @method string  getTitle()         Returns the current record's "title" value
 * @method string  getDescription()   Returns the current record's "description" value
 * @method string  getContent()       Returns the current record's "content" value
 * @method string  getImage()         Returns the current record's "image" value
 * @method string  getAdvertisement() Returns the current record's "advertisement" value
 * @method Slide   setIdslide()       Sets the current record's "idslide" value
 * @method Slide   setTitle()         Sets the current record's "title" value
 * @method Slide   setDescription()   Sets the current record's "description" value
 * @method Slide   setContent()       Sets the current record's "content" value
 * @method Slide   setImage()         Sets the current record's "image" value
 * @method Slide   setAdvertisement() Sets the current record's "advertisement" value
 * 
 * @package    quanaudio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlide extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slide');
        $this->hasColumn('idslide', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('description', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('image', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('advertisement', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}