<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cart', 'doctrine');

/**
 * BaseCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idcart_item
 * @property integer $iduser
 * @property timestamp $updated
 * @property CartItem $CartItem
 * @property User $User
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getIdcartItem()  Returns the current record's "idcart_item" value
 * @method integer   getIduser()      Returns the current record's "iduser" value
 * @method timestamp getUpdated()     Returns the current record's "updated" value
 * @method CartItem  getCartItem()    Returns the current record's "CartItem" value
 * @method User      getUser()        Returns the current record's "User" value
 * @method Cart      setId()          Sets the current record's "id" value
 * @method Cart      setIdcartItem()  Sets the current record's "idcart_item" value
 * @method Cart      setIduser()      Sets the current record's "iduser" value
 * @method Cart      setUpdated()     Sets the current record's "updated" value
 * @method Cart      setCartItem()    Sets the current record's "CartItem" value
 * @method Cart      setUser()        Sets the current record's "User" value
 * 
 * @package    quanaudio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCart extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cart');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idcart_item', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('iduser', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CartItem', array(
             'local' => 'idcart_item',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'iduser',
             'foreign' => 'iduser'));
    }
}