<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Category', 'doctrine');

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcategory
 * @property string $name
 * @property Doctrine_Collection $News
 * 
 * @method integer             getIdcategory() Returns the current record's "idcategory" value
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getNews()       Returns the current record's "News" collection
 * @method Category            setIdcategory() Sets the current record's "idcategory" value
 * @method Category            setName()       Sets the current record's "name" value
 * @method Category            setNews()       Sets the current record's "News" collection
 * 
 * @package    quanaudio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('idcategory', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('News', array(
             'local' => 'idcategory',
             'foreign' => 'idcategory'));
    }
}