# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
# custome route
get_slide:
  url:   /get-slides
  param: { module: api, action: getSlides }
get_slide_detail:
  url:   /get-slide-detail/:id
  param: { module: api, action: getSlideDetail }
put_update_slide:
  url:   /update-slide/:id
  param: { module: api, action: updateSlide, id: ''}
get_menu_type:
  url:   /get-menu-types
  param: { module: api, action: getTypesMenu }
get_audios:
  url:   /get-audios
  param: { module: api, action: getAudios }
get_audio:
  url:   /get-audio/:id
  param: { module: api, action: getAudio, id: ''}
get_audio_by_type:
  url:   /get-audio-by-type/:idtype
  param: { module: api, action: getAudioByType, idtype: ''}
get_cart_items:
  url:   /get-cart-items/:ids
  param: { module: api, action: getCartItems, ids: ''}
post_checkout:
  url:   /post-checkout
  param: { module: api, action: postCheckout }
get_latest_news:
  url:   /get-latest-news/:type
  param: { module: api, action: getLatestNews, type: ''}
get_detail_new:
  url:   /get-detail-new/:id
  param: { module: api, action: getDetailNew, id: ''}
get_random_new:
  url:   /get-random-new/:id
  param: { module: api, action: getRandomNew, id: ''}
get_random_audio:
  url:   /get-random-audio/:id
  param: { module: api, action: getRandomAudio, id: ''}
# ========admin router===========
post_login:
  url:   /login
  param: { module: api, action: postLogin}
post_product:
  url:   /add-new-product
  param: { module: api, action: postAddProduct}
delete_product:
  url:   /delete-product/:id
  param: { module: api, action: deleteProduct, id: ''}
put_update_image:
  url:   /update-image/:id
  param: { module: api, action: updateImageSrc, id: ''}
put_update_audio:
  url:   /update-audio/:id
  param: { module: api, action: updateAudio, id: ''}
post_news:
  url:   /add-new-news
  param: { module: api, action: postNews}
delete_news:
  url:   /delete-news/:id
  param: { module: api, action: deleteNews, id: ''}
put_update_news:
  url:   /update-news/:id
  param: { module: api, action: updateNews, id: ''}
# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*