<?php

/**
 * AudioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AudioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AudioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Audio');
    }

    public static function getAudios(){
        $audios = AudioTable::getInstance()
            ->createQuery('a')
            ->select('a.*')
            ->fetchArray();
        return $audios;
    }

    public static function getCartItems($ids){
        $audios = AudioTable::getInstance()
            ->createQuery('a')
            ->select('a.*')
            ->whereIn('a.idaudio', $ids)
            ->fetchArray();
        return $audios;
    }

    public static function getAudioById($id){
        $audio = AudioTable::getInstance()
            ->createQuery('a')
            ->select('a.*')
            ->where('a.idaudio = ?', $id)
            ->fetchArray();
        return $audio[0];
    }

    public static function getAudioByType($idtype){
        $audio = AudioTable::getInstance()
            ->createQuery('a')
            ->select('a.*')
            ->where('a.idtype = ?', $idtype)
            ->fetchArray();
        return $audio;
    }
}