<?php

/**
 * PhonenumbersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhonenumbersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhonenumbersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Phonenumbers');
    }
}